services:
  - type: web
    name: book-explorer-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: <your-mongodb-uri>
  - type: worker
    name: book-explorer-scraper
    env: node
    rootDir: scraper
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: <your-mongodb-uri>